name: Tests
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/gradle-build-action@v2

      - name: Check
        run: ./gradlew --no-daemon check

      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/reports
